default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: redmine
  password: "135790"
  host:  localhost
  port: 5432

development:
  <<: *default
  database: db/development.sqlite3
  database: redmine_db

test:
  <<: *default
  database: db/test.sqlite3
  database: redmine_db

production:
  <<: *default
  database: db/production.sqlite3
  database: redmine_db
